project:
  type: website
  output-dir: docs

website:
  title: "Kostiantyn Dreval: Software Engineering, Data Science, Bioinformatics, and Computational Biology"
  image: src/images/KD_default.png
  favicon: src/images/KD_white.png
  back-to-top-navigation: true
  page-navigation: true
  search: true
  navbar:
    background: "#A3B18A"
    logo: src/images/KD_default.png
    logo-alt: "Kostiantyn Dreval"
    title: Kostiantyn Dreval
    collapse-below: lg
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: https://github.com/Kdreval/cv/blob/master/cv.pdf
  page-footer:
    background: "#588157"
    left: |
      Copyright 2024,
      ![](src/images/KD_white.png){fig-alt="Kostiantyn Dreval" width=25px}
      Kostiantyn Dreval

    right:
      - icon: github
        href: https://github.com/Kdreval
      - icon: linkedin
        href: https://www.linkedin.com/in/kostiantyn-dreval-05718bba/
      - icon: code
        href: https://orcid.org/0000-0002-6214-2843
      - icon: lightbulb
        href: https://scholar.google.com/citations?user=5noD2aEAAAAJ&hl=en
      - icon: folder
        href: https://pubmed.ncbi.nlm.nih.gov/?term=dreval+k&sort=date

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    grid:
      margin-width: 100px
