project:
  type: website
  output-dir: docs

website:
  title: "My portfolio"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - motion_graphics.qmd
  page-footer:
    background: light
    left: "Copyright 2023, Kostia Dreval"
    right:
      - icon: github
        href: https://github.com/Kdreval
      - icon: facebook
        href: https://www.facebook.com/kostiantyn.dreval/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



