project:
  type: website
  output-dir: docs

website:
  title: "My portfolio"
  image: src/images/odlogo.jpg
  favicon: src/images/odlogo.jpg
  back-to-top-navigation: true
  page-navigation: true
  search: false
  navbar:
    background: "#000000"
    logo: src/images/odlogo.jpg
    logo-alt: "Kostia Dreval"
    title: false
    collapse-below: lg
    right:
      - index.qmd
      - about.qmd
      - text: "Graphic Design"
        menu:
        - text: "Motion Graphics"
          href: motion_graphics.qmd
        - text: "Social Media"
          href: motion_graphics.qmd
  page-footer:
    background: "#000000"
    left: "Copyright 2023, Kostia Dreval"
    right:
      - icon: github
        href: https://github.com/Kdreval
      - icon: facebook
        href: https://www.facebook.com/kostiantyn.dreval/

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    grid:
      margin-width: 100px



